version: '2'
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
     - 1433:1433
    environment:
     - ACCEPT_EULA=Y
     - MSSQL_PID=Standard
     - SA_PASSWORD=Password!
     - MSSQL_AGENT_ENABLED=true

  zookeeper:
    image: confluentinc/cp-zookeeper:5.5.3
    container_name: zookeerper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - '2181:2181'

  kafka:
    image: confluentinc/cp-enterprise-kafka:5.5.3
    container_name: kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9095,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    links:
      - zookeeper
    ports:
      - '9092:9092'
      - '9095:9095'
      
  kafka-connect:
      container_name: kafka-connect
      image: debezium/connect:2.0
      ports:
        - '8083:8083'
      links:
        - kafka
        - zookeeper
      environment:
         - BOOTSTRAP_SERVERS=kafka:9095
         - GROUP_ID=medium_debezium
         - CONFIG_STORAGE_TOPIC=my_connect_configs
         - CONFIG_STORAGE_REPLICATION_FACTOR=1
         - OFFSET_STORAGE_TOPIC=my_connect_offsets
         - OFFSET_STORAGE_REPLICATION_FACTOR=1
         - STATUS_STORAGE_TOPIC=my_connect_statuses
         - STATUS_STORAGE_REPLICATION_FACTOR=1
         - REST_ADVERTISED_HOST_NAME=medium_debezium
